### ISSUE TITLE
node-proxy-agent adds a huge amount to load time and installed size

### ISSUE THREAD

**Issue by starpit** [apache/incubator-openwhisk-client-js#158]
the latest openwhisk npm increased load time tremendously. it also increased the npm install'd size from 1.1MB to 7.5MB

here is the time to load the top-level dependencies in client.js:

```
messages +1ms
openwhisk_error +1ms
needle +28ms
url +0ms
http +0ms
proxy-agent +119ms
```

the last bit is the new dependence in the just-released openwhisk

+6.4MB and a huge increase in load time for a dependence that is optional. not to mention that needle supports proxies directly, does it not?

c.f. https://github.com/apache/incubator-openwhisk-client-js/pull/147

**Comment by starpit** [comment]
it's also worth noting that the `tls` indirect dependence  (openwhisk -> proxy-agent -> pac-proxy-agent -> get-uri -> ftp -> tls) is seemingly incompatible with webpack builds (note how openwhisk is now loading an ftp library, potentially on each and every function invocation!)

**Comment by jthomas** [comment]
oh damn - thanks for catching this @starpit. Let me look into this and get back to you. This is not ideal!

**Comment by jthomas** [comment]
Looking into this some more... it's clear adding the `proxy-agent` dependency causes an unacceptable increase in dependency size and load time. I do think supporting HTTP proxies is a valid requirement and we do want to still support this.

https://packagephobia.now.sh/result?p=proxy-agent

Install size has jumped from under 1MB to over 5MB. 
https://packagephobia.now.sh/result?p=openwhisk@3.19.0

I have a few ideas about how to resolve this, want to open it up for community involvement to decide the best way forward.

1. Allow user to pass in exact `http.Agent` implementation class in constructor, rather than providing the implementation in the library.

2. Remove `proxy-agent` dependency and replace with underlying `http-proxy-agent` and `https-proxy-agent` deps this project relies on. 

Does anyone have any other suggestions? 

Given the vast majority of users will not need a HTTP proxy, I'd like to keep the "fast path" as light as possible and this means option 1). seems like the best choice. This does make it a bit more difficult for downstream tools like The Serverless Framework (where the SDK is used implicitly) but that's a trade-off I think we have to make. Those tools will have to manage this in their projects. 

I've also opened some other issues to help make sure this kind of issue [doesn't happen again](https://github.com/apache/incubator-openwhisk-client-js/issues/159) and also [reduce build size](https://github.com/apache/incubator-openwhisk-client-js/issues/160) even further.

**Comment by rabbah** [comment]
Since needle has some builtin proxy support and you can pass a custom http agent (documented on the npm page), does that work? Is that what you’re proposing?

**Comment by jthomas** [comment]
@rabbah Yes, that's option 1). User would include proxy they require manually in their app deps and pass that instance to the OW constructor, which we'd pass through to needle.

**Comment by csantanapr** [comment]
I agree remove lib dependency and document 2 things with simple example how to initialize ow 
1) how to configure needle proxy
2) how to configure custom proxy such as http-agent

**Comment by jthomas** [comment]
FYI @karanrk

**Comment by starpit** [comment]
fwiw, the way i debug load time is by adding a `debug` call between each `require`. this is how i got the +xxx ms data above (the numbers were quite stable across runs). there is already an open issue for adding `debug` calls more generally #120, maybe we can piggyback these interstitial load-time calls on that work item.

then, a fairly straightforward script along with some basic quotas would let us lock down initialization time regressions.
