### ISSUE TITLE
integration tests require manual setup and cleanup

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-client-js#2]
In order for a dev to run the integration tests, one has to create seed artifacts manually. Further, if a test fails, its transient artifacts are not reclaimed. The integration tests should perform all required setup and cleanup on termination.

**Comment by csantanapr** [comment]
I was not able to run the integrations tests running `npm run test-integration`

**Comment by jthomas** [comment]
@csantanapr Can you provide more details about what exactly failed? 

I have run them recently and didn't have any issues but that's using my setup :)

**Comment by csantanapr** [comment]
Could you try setting up travis and see what you come up with?

There are no instructions what environment variables I need to set before running the tests, namespace should not be required, user should be able to just use `_` but the tests query the api and use the namespace value `carlos@email.com_dev` to check

Also I had a package demo/ with action hello in my namespace, one of the tests failed to list actions, since doing a get on the action returns `namespace:carlos@email.com_dev/demo` NS plus package and the test always assume that there is no package present in `namespace` field.

This is all I recall, if we setup travis integration, meaning deploying openwhisk, and then running the tests using the guest ow key, it should reveal how to run the tests and what instructions we need to document for a contributor trying to run test locally before sending a PR.

**Comment by jthomas** [comment]
Did you see these instructions?
https://github.com/openwhisk/openwhisk-client-js/tree/master/test/integration

I've been using a "test" namespace with the assets in to isolate the results.

**Comment by csantanapr** [comment]
No I didn't saw them 🤦‍♂️ 

But they are manual steps we should not have any manual steps
And user should not set namespace value we should use _ and then use the ok to get the namespace value

**Comment by jthomas** [comment]
We should put a note in the README.md with a link to that document.

**Comment by bjustin-ibm** [comment]
Resolved by #59
